language: python

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

matrix:
  allow_failures:
    - python: 3.6
  include:
    - python: 2.7
      env: GO=1.10.x
    - python: 2.7
      env: GO=1.11.x
    - python: 2.7
      env: GO=1.10.x
      os: osx
      install: brew install --upgrade go@${GO}
    - python: 3.6
      env: GO=1.10.x

install:
  - |
    export GOPATH=~/gopath
    export PATH="$GOPATH/bin:$PATH"
    export TRAVIS_BUILD_DIR="$GOPATH/src/github.com/$TRAVIS_REPO_SLUG"
    mkdir -p "$TRAVIS_BUILD_DIR"
    rsync -az . "$TRAVIS_BUILD_DIR"
    cd "$TRAVIS_BUILD_DIR"
    eval "$(gimme $GO)"

before_script:
  - go version && python --version && python -m pip --version
  - go get -t
  - go test -v
  - pip install --upgrade pip

script: true
