language: python

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

matrix:
  allow_failures:
    - python: 3.6
    - env: GO="stable"
  include:
    - python: 2.7
      env: GO="1.10.x"  # "1.10.x" does NOT work :-(
    - python: 2.7
      env: GO="1.11.x"
    - python: 2.7
      env: GO="stable"  # Currently "1.11"
    - python: 2.7
      env: GO="1.10.4"
      os: osx
      before_install: brew install --upgrade gimme
    - python: 3.6
      env: GO="1.10.4"

install:
  - |
    export GOPATH=~/gopath
    export PATH="$GOPATH/bin:$PATH"
    export TRAVIS_BUILD_DIR="$GOPATH/src/github.com/$TRAVIS_REPO_SLUG"
    mkdir -p "$TRAVIS_BUILD_DIR"
    rsync -az . "$TRAVIS_BUILD_DIR"
    cd "$TRAVIS_BUILD_DIR"
    eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=${GO} bash)"

before_script:
  - go version && python --version && python -m pip --version
  - go get -t
  - go test -v
  - pip install --upgrade pip

script: true
