language:
  - go
  - python  # This does not really work :-(

addons:
  apt:
    sources: deadsnakes
    update: true
    packages:
      - python
      - python-pip
      - python3
      - python3-pip

#matrix:
#  allow_failures:
#    - python: 3.6
#  include:
#    - language: python
#      go: "1.10.x"
#      python: 2.7
#      env: PIP_SUDO=""
#    - language: python
#      go: "1.10.x"
#      python: 3.6
#      env: PIP_SUDO=""
#    - os: osx
#      env: PIP_SUDO="sudo"

before_script:
  - go version
  #- dpkg -L golang-1.10-go  # --> /usr/lib/go-1.10/bin/go
  - dpkg -L python   # --> /usr/share/python
  - dpkg -L python3  # --> /usr/share/python
  #- dpkg -L python3-pip python3-pip  # --> 
  - PATH=/usr/share:${PATH}
  #- go version
  - ls /usr/share/python
  - ls -r /usr/share/python3
  - python  --version && python  -m pip --version
  - python3 --version && python3 -m pip --version
  - sudo python3 -m pip install --upgrade pip
  #- sudo python2 -m ensurepip --upgrade
  - sudo python  -m pip install --upgrade pip

script: true
