language:
  - go

addons:
  apt:
    sources: deadsnakes
    update: true
    packages:
      - python
      - python-pip
      - python3.6
      - python3.6-venv
 
matrix:
  allow_failures:
    - python: 3.6
  include:
     - python: 2.7
     - python: 3.6

before_script:
  - echo ${TRAVIS_PYTHON_VERSION}
  - python${TRAVIS_PYTHON_VERSION} --version
  - python${TRAVIS_PYTHON_VERSION} -m pip --version

script: true
